name: Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug secrets
      run: |
        echo "DOCKERHUB_USERNAME is: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "DOCKERHUB_TOKEN length: ${#DOCKERHUB_TOKEN}"
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker image tag
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}  # first 7 characters of commit hash
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -f Dockerfile \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:${{ env.IMAGE_TAG }} \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest .

    - name: Push Docker image (commit hash)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:${{ env.IMAGE_TAG }}

    - name: Push Docker image (latest)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest
